name: hyotan
description: CSVデータ収集アプリ
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
  share_plus: ^7.2.1
  csv: ^5.0.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
