name: hyotan
description: CSVデータ収集アプリ
publish_to: 'none'
version: 1.0.13

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.0
  path: ^1.9.0
  provider: ^6.1.2
  share_plus: ^11.0.0
  csv: ^5.0.2
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  path_provider: ^2.1.2
  google_mobile_ads: ^5.0.0
  flutter_localizations:
    sdk: flutter
  horizontal_data_table: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
